#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
APP="$1"; INTERNAL_PORT="$2"; INTERNAL_IP_ADDRESS="$3"; IMAGE_TAG="$4"; IMAGE=$(get_app_image_name $APP $IMAGE_TAG); CONNECT_NETWORK="$DOKKU_ROOT/$APP/DOKKU_CONNECT_NETWORK"
verify_app_name "$APP"

if [[ -f "$CONNECT_NETWORK" ]]; then
  NETWORK_NAME=`cat $CONNECT_NETWORK`
  dokku_log_info1 "Attach the network $NETWORK_NAME to containers"
  docker ps -f ancestor=$IMAGE -q | xargs -n1 docker network connect $NETWORK_NAME
fi
